
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: grafana-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: grafana/admin
        property: username
    - secretKey: password
      remoteRef:
        key: grafana/admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-alert-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: prometheus-alert-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook_url
      remoteRef:
        key: prometheus/alertmanager
        property: webhook_url
    - secretKey: auth_token
      remoteRef:
        key: prometheus/alertmanager
        property: auth_token
